In [1]:
import os
import numpy as np

from collections import Counter

## Saved events:

In [2]:
filespath = '/Users/carmenromoluque/nexus_petit_analysis/full-body-PET/statistics/data_statistics/'
fname     = 'full_body_statistics_'

depths = [3, 4]

saved_events = []
for j,d in enumerate(depths):
    filename2  = filespath + f'/full_body_depth{d}cm/full_body_{d}cmdepth_counting_evts_0_1000.npz'
    data2      = np.load(filename2, allow_pickle=True)
    saved_evts = data2['saved_event']
    saved_events.append(np.sum(saved_evts))

saved_events = np.array(saved_events)

In [3]:
saved_events

array([2468980, 3222594])

### Data coincidences

In [4]:
#filepath = '/Users/carmenromoluque/nexus_petit_analysis/full-body-PET/4cm_depth/data_statistics_coinc/'
filepath = '/Users/carmenromoluque/nexus_petit_analysis/full-body-PET/4cm_depth/'
#filepath = '/Users/carmenromoluque/nexus_petit_analysis/full-body-PET/statistics/data_statistics/full_body_depth3cm/data_statistics_coinc/'

true_r1, true_phi1, true_z1    = [], [], []
true_r2, true_phi2, true_z2    = [], [], []
reco_r1, reco_phi1, reco_z1    = [], [], []
reco_r2, reco_phi2, reco_z2    = [], [], []
touched_sipms1, touched_sipms2 = [], []
sns_response1, sns_response2   = [], []
true_t1, true_t2               = [], []
first_sipm1, first_sipm2       = [], []
first_time1, first_time2       = [], []
c0, c1, c2, c3, c4             = 0, 0, 0, 0, 0
event_ids                      = []

#start     = 880
#num_files = 120
#step      = 10
#for number in range(start, start+num_files, step):
#        my_file  = f"{filepath}/full_body_statistics_coinc_reco_info_{number}_{step}_2_4_4_2.npz"
for filename in os.listdir(filepath):
    if filename.endswith('2_4_4_2.npz'):
        my_file = filepath+filename
        d   = np.load(my_file)
        #for keys, vals in d.items():
        #    print(keys)
        
        true_r1   = np.concatenate((true_r1,   d['a_true_r1']))
        true_phi1 = np.concatenate((true_phi1, d['a_true_phi1']))
        true_z1   = np.concatenate((true_z1,   d['a_true_z1']))   
            
        reco_r1   = np.concatenate((reco_r1,   d['a_reco_r1']))
        reco_phi1 = np.concatenate((reco_phi1, d['a_reco_phi1']))  
        reco_z1   = np.concatenate((reco_z1,   d['a_reco_z1']))  
        
        true_r2   = np.concatenate((true_r2,   d['a_true_r2']))
        true_phi2 = np.concatenate((true_phi2, d['a_true_phi2']))
        true_z2   = np.concatenate((true_z2,   d['a_true_z2']))   
            
        reco_r2   = np.concatenate((reco_r2,   d['a_reco_r2']))
        reco_phi2 = np.concatenate((reco_phi2, d['a_reco_phi2']))  
        reco_z2   = np.concatenate((reco_z2,   d['a_reco_z2']))
        
        true_t1 = np.concatenate((true_t1, d['a_true_time1']))
        true_t2 = np.concatenate((true_t2, d['a_true_time2']))
        
        sns_response1 = np.concatenate((sns_response1, d['a_sns_response1']))
        sns_response2 = np.concatenate((sns_response2, d['a_sns_response2']))
        
        touched_sipms1 = np.concatenate((touched_sipms1, d['a_touched_sipms1']))
        touched_sipms2 = np.concatenate((touched_sipms2, d['a_touched_sipms2']))
        
        first_sipm1 = np.concatenate((first_sipm1, d['a_first_sipm1']))
        first_sipm2 = np.concatenate((first_sipm2, d['a_first_sipm2']))
        
        first_time1 = np.concatenate((first_time1, d['a_first_time1']))
        first_time2 = np.concatenate((first_time2, d['a_first_time2']))
        
        event_ids = np.concatenate((event_ids, d['a_event_ids']))
        
        c0 += d['c0'] #if len(pos1) == 0 or len(pos2) == 0
        c1 += d['c1'] #if len(pos1r) == 0 or len(pos2r) == 0
        c2 += d['c2'] #if len(q1phi) == 0 or len(q2phi) == 0
        c3 += d['c3'] #if len(q1z) == 0 or len(q2z) == 0
        c4 += d['c4'] #if len(q1e) == 0 or len(q2e) == 0

        
true_r1   = np.array(true_r1)
true_phi1 = np.array(true_phi1)
true_z1   = np.array(true_z1)

reco_r1   = np.array(reco_r1)
reco_phi1 = np.array(reco_phi1)
reco_z1   = np.array(reco_z1)

true_r2   = np.array(true_r2)
true_phi2 = np.array(true_phi2)
true_z2   = np.array(true_z2)

reco_r2   = np.array(reco_r2)
reco_phi2 = np.array(reco_phi2)
reco_z2   = np.array(reco_z2)

true_t1 = np.array(true_t1) 
true_t2 = np.array(true_t2)

first_sipm1 = np.array(first_sipm1)
first_sipm2 = np.array(first_sipm2)
first_time1 = np.array(first_time1)
first_time2 = np.array(first_time2)

sns_response1 = np.array(sns_response1)
sns_response2 = np.array(sns_response2)

event_ids = np.array(event_ids)

true_x1 = true_r1 * np.cos(true_phi1)
reco_x1 = reco_r1 * np.cos(reco_phi1)
true_y1 = true_r1 * np.sin(true_phi1)
reco_y1 = reco_r1 * np.sin(reco_phi1)
true_x2 = true_r2 * np.cos(true_phi2)
reco_x2 = reco_r2 * np.cos(reco_phi2)
true_y2 = true_r2 * np.sin(true_phi2)
reco_y2 = reco_r2 * np.sin(reco_phi2)

In [47]:
print(c0, c1, c2, c3, c4)

2214068 0 0 0 0


In [48]:
print(len(event_ids), 'coincidences')

254912 coincidences


In [49]:
event_ids

array([22650008., 22650032., 22650046., ..., 14972453., 14972469.,
       14972485.])

In [50]:
len(event_ids)

254912

### Data statistics events:

In [8]:
#filepath = '/Users/carmenromoluque/nexus_petit_analysis/full-body-PET/4cm_depth/data_statistics_evts/'
filepath = '/Users/carmenromoluque/nexus_petit_analysis/full-body-PET/statistics/data_statistics/full_body_depth4cm/'
#filepath = '/Users/carmenromoluque/nexus_petit_analysis/full-body-PET/statistics/data_statistics/full_body_depth3cm/data_statistics_evts/'

evt_ids            = []
compt_events       = []
dist_first_hit_ave = []
phot_events        = []

#start     = 880
#num_files = 120
#step      = 1
#for number in range(start, start+num_files, step):
#        my_file  = f"{filepath}/full_body_statistics_{number}_{step}_2.npz"        
for filename in os.listdir(filepath):
    if filename.endswith('0_10_2.npz'):
        print(filename)
        my_file = filepath+filename
        d   = np.load(my_file)
        #for keys, vals in d.items():
        #    print(keys)
        evt_ids            = np.concatenate((evt_ids    , d['evt_ids']))
        phot_events        = np.concatenate((phot_events, d['phot_events']))
        for i in d['compt_events']:
            compt_events.append(i)
        for i in d['dist_first_hit_ave']:
            dist_first_hit_ave.append(i)

evt_ids            = np.array(evt_ids           )
compt_events       = np.array(compt_events      )
dist_first_hit_ave = np.array(dist_first_hit_ave)
phot_events        = np.array(phot_events       )

full_body_statistics_0_10_2.npz


In [9]:
print(len(evt_ids), len(compt_events), len(dist_first_hit_ave), len(phot_events))

3163 3163 3163 3163


In [10]:
assert evt_ids.all() == event_ids.all()

AssertionError: 

In [11]:
np.setdiff1d(evt_ids, event_ids)

array([0.00000e+00, 2.00000e+00, 1.10000e+01, ..., 2.73061e+05,
       2.73073e+05, 2.73098e+05])

In [55]:
print(len(evt_ids), len(event_ids))

254912 254912


In [57]:
len(evt_ids)*100/saved_events[0]

10.32458748147008

## Phot

In [56]:
Counter(np.sort(phot_events))

Counter({0.0: 149803, 1.0: 91272, 2.0: 13837})

## Is there any true phot evt which has been labeled as compt?

In [58]:
num0 = 0
for ph, comp, evt, dist in zip(phot_events, compt_events, evt_ids, dist_first_hit_ave):
    if ph==2:
        if comp[0]==True or comp[1]==True:
            num0 += 1
            print(comp, evt, dist)
print(num0)

[ True False] 7861218.0 [0.00028669 0.        ]
[ True False] 7922360.0 [0.00025269 0.        ]
[ True False] 7950500.0 [6.99245575e-05 0.00000000e+00]
[ True False] 630161.0 [9.28155932e-05 0.00000000e+00]
[ True False] 28710544.0 [6.13027878e-05 0.00000000e+00]
[ True False] 24480932.0 [0.00015561 0.        ]
[ True False] 9752075.0 [0. 0.]
[ True False] 20971025.0 [7.03654005e-05 0.00000000e+00]
[ True False] 13561434.0 [7.62939453e-05 0.00000000e+00]
[ True False] 13681623.0 [0.00050906 0.        ]
[ True False] 13770846.0 [1.7059845e-05 0.0000000e+00]
[ True False] 19260624.0 [5.70931625e-05 0.00000000e+00]
[ True False] 19351671.0 [0. 0.]
[ True False] 21030739.0 [0. 0.]
[ True False] 21211640.0 [0.00060484 0.        ]
[ True False] 4770272.0 [0. 0.]
[ True False] 27960265.0 [0. 0.]
[ True False] 27991767.0 [0. 0.]
[ True False] 1201991.0 [0.00011899 0.        ]
[ True False] 26161049.0 [5.95874772e-05 0.00000000e+00]
[ True False] 26221715.0 [0.00020243 0.        ]
[ True False]

## Percentages:

In [169]:
100*len(evt_ids)/saved_events[1]

9.775168699501085

#### Single phot + compt (compt or phot like)

In [173]:
single_sel     = (phot_events == 1)
compt_sing_sel = compt_events[single_sel]

In [174]:
len(compt_sing_sel)

110511

In [181]:
num1 = 0
single_com = 0
single_phot_like = 0
for com,d in zip(compt_sing_sel, dist_first_hit_ave):
    if com[0]==True and com[1]==True:
        continue
    elif com[0]==True or com[1]==True:
        num1 += 1
    if com[0]==True:
        if d[0] > 1:
            single_com += 1
        else:
            single_phot_like += 1
    if com[1]==True:
        if d[1] > 1:
            single_com += 1
        else:
            single_phot_like += 1
            
print(num1)
print('single Compton', single_com      )
print('single phot-like', single_phot_like)

98421
single Compton 33891
single phot-like 64530


In [190]:
num2*100/len(evt_ids)

48.25690286780905

In [179]:
33891 + 64530

98421

In [185]:
33891 * 31.24/98421 # + 20.48

10.757407870271587

In [197]:
num2 = 0
doubl_no_comp_sel = []
for com in compt_events:
    if com[0]==False and com[1]==False:
        num2 += 1
        doubl_no_comp_sel.append(True)
    else:
        doubl_no_comp_sel.append(False)
            
print(num2)

29328


In [198]:
phot_no_comp_sel  = phot_events[doubl_no_comp_sel]

In [200]:
Counter(np.sort(phot_no_comp_sel))

Counter({0.0: 1994, 1.0: 11466, 2.0: 15868})

In [31]:
38006*100/len(evt_ids)

12.064860609369742

## Single phot + Compt

In [13]:
num3, num4, num5, num6 = 0, 0, 0, 0
for ph,c,d,e in zip(phot_events, compt_events, dist_first_hit_ave, evt_ids):
    if ph ==1:
        if d[0]==0 and d[1]==0:
            print(e, 'phot-like')
            num3 += 1 #phot-like
        elif d[0]>1 and d[1]>1:
            print(e, 'compt')
            num4 += 1 #compt
        elif d[0]>1 or d[1]>1:
            num5 += 1 #compt
            print(e, 'compt')
        else:
            num6 +=1 #phot-like
            print(e, 'phot-like')

30.0 phot-like
42.0 compt
87.0 phot-like
130.0 compt
144.0 phot-like
146.0 compt
162.0 phot-like
166.0 phot-like
189.0 compt
217.0 compt
220.0 phot-like
243.0 phot-like
245.0 phot-like
262.0 compt
267.0 phot-like
287.0 compt
343.0 compt
454.0 phot-like
488.0 phot-like
535.0 phot-like
543.0 phot-like
558.0 compt
559.0 phot-like
620.0 compt
650.0 phot-like
718.0 phot-like
742.0 phot-like
862.0 compt
918.0 compt
932.0 phot-like
977.0 compt
1020.0 phot-like
1051.0 compt
1068.0 phot-like
1083.0 phot-like
1187.0 phot-like
1215.0 phot-like
1261.0 phot-like
1270.0 phot-like
1323.0 phot-like
1364.0 phot-like
1387.0 compt
1476.0 phot-like
1490.0 compt
1491.0 compt
1497.0 compt
1499.0 phot-like
1504.0 phot-like
1540.0 phot-like
1542.0 phot-like
1561.0 compt
1578.0 phot-like
1592.0 phot-like
1627.0 compt
1715.0 compt
1717.0 phot-like
1734.0 compt
1749.0 compt
1757.0 compt
1779.0 phot-like
1796.0 phot-like
1836.0 compt
1839.0 compt
1842.0 phot-like
1862.0 compt
1894.0 compt
1919.0 compt
2015.0 comp

181692.0 phot-like
181722.0 phot-like
181745.0 compt
181820.0 phot-like
181876.0 phot-like
181882.0 compt
181891.0 phot-like
181919.0 phot-like
181941.0 phot-like
181944.0 phot-like
182005.0 phot-like
182013.0 compt
182079.0 phot-like
182094.0 compt
182151.0 phot-like
182260.0 phot-like
182308.0 phot-like
182315.0 compt
182334.0 phot-like
182368.0 compt
182433.0 phot-like
182435.0 compt
182444.0 phot-like
182454.0 compt
182473.0 compt
182489.0 phot-like
182506.0 compt
182531.0 phot-like
182694.0 phot-like
182700.0 phot-like
182709.0 phot-like
182749.0 phot-like
182752.0 compt
182763.0 phot-like
182799.0 phot-like
182812.0 phot-like
182856.0 compt
182864.0 compt
182882.0 phot-like
182895.0 phot-like
182910.0 compt
182914.0 phot-like
182987.0 phot-like
183002.0 phot-like
183004.0 compt
183010.0 phot-like
183023.0 phot-like
183040.0 phot-like
183097.0 phot-like
183111.0 phot-like
183142.0 phot-like
210010.0 phot-like
210107.0 phot-like
210126.0 phot-like
210127.0 compt
210143.0 phot-like


In [60]:
print(num3, num4, num5, num6)
num3 + num4+ num5+ num6

19065 0 27707 44500


91272

In [63]:
19065 + 44500

63565

## Non phot means compt??

In [64]:
phot_like_evt2 = []
compton_evt2   = []
no_one2        = []
num7           = 0
for ph,c,d,e in zip(phot_events, compt_events, dist_first_hit_ave, evt_ids):
    if ph ==0:
        if d[0]==0 and d[1]==0:
            num7 += 1 # 2 phot-like
        #elif d[0]>1 and d[1]>1:
        #    num4 += 1
        #elif d[0]>1 or d[1]>1:
        #    num5 += 1
        #else:
        #    num6 +=1 #phot-like
        if d[0] > 1:
            if d[1] > 1:
                no_one2       .append(0)
                compton_evt2  .append(2)
                phot_like_evt2.append(0)
            else:
                no_one2       .append(0)
                compton_evt2  .append(1)
                phot_like_evt2.append(1)
        else:
            if d[1] > 1:
                no_one2       .append(0)
                compton_evt2  .append(1)
                phot_like_evt2.append(1)
            else:
                no_one2       .append(0)
                compton_evt2  .append(0)
                phot_like_evt2.append(2)                

a_phot_like_evt2 = np.array(phot_like_evt2)
a_compton_evt2   = np.array(compton_evt2  )
a_no_one2        = np.array(no_one2       )

In [66]:
num7

6753

In [65]:
Counter(np.sort(a_compton_evt2))

Counter({0: 72654, 1: 63487, 2: 13662})

In [67]:
Counter(np.sort(a_phot_like_evt2))

Counter({0: 13662, 1: 63487, 2: 72654})

In [69]:
Counter(np.sort(no_one2))

Counter({0: 149803})

In [68]:
13662+63487+72654

149803

In [217]:
Counter(np.sort(phot_events))

Counter({0.0: 188436, 1.0: 110511, 2.0: 16067})

In [45]:
84523*100/len(evt_ids)

26.83150590132502

In [44]:
59.81 - 6.96 - 26.03

26.82